"""empty message

Revision ID: 0438b05db7ff
Revises: 3932a6ac8181
Create Date: 2025-05-28 18:32:06.319291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0438b05db7ff'
down_revision = '3932a6ac8181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bloqueo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bloqueado', sa.Boolean(), nullable=False))
        batch_op.drop_column('motivo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bloqueo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('bloqueado')

    # ### end Alembic commands ###
