"""empty message

Revision ID: 091a29e6602f
Revises: 5bc074892c2b
Create Date: 2025-05-28 18:15:39.839639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091a29e6602f'
down_revision = '5bc074892c2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloqueo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bloqueo')
    # ### end Alembic commands ###
