"""empty message

Revision ID: 0a558e17a78b
Revises: 
Create Date: 2025-07-02 15:42:44.596916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a558e17a78b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloqueo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('bloqueado', sa.Boolean(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('servicio', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bloqueo', schema=None) as batch_op:
        batch_op.create_index('unique_fecha_hora_bloqueo', ['fecha', 'hora'], unique=True)

    op.create_table('reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('servicio', sa.String(length=100), nullable=True),
    sa.Column('token', sa.String(length=50), nullable=False),
    sa.Column('cancelada', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.create_index('unique_fecha_hora_active_reservas', ['fecha', 'hora'], unique=True, postgresql_where=sa.text('cancelada = false'))

    op.create_table('testimonio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=False),
    sa.Column('estrellas', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testimonio')
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.drop_index('unique_fecha_hora_active_reservas', postgresql_where=sa.text('cancelada = false'))

    op.drop_table('reserva')
    with op.batch_alter_table('bloqueo', schema=None) as batch_op:
        batch_op.drop_index('unique_fecha_hora_bloqueo')

    op.drop_table('bloqueo')
    # ### end Alembic commands ###
