"""empty message

Revision ID: 16f803863e06
Revises: 091a29e6602f
Create Date: 2025-05-28 18:18:21.481012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16f803863e06'
down_revision = '091a29e6602f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bloqueo', schema=None) as batch_op:
        batch_op.create_index('unique_fecha_hora_bloqueo', ['fecha', 'hora'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bloqueo', schema=None) as batch_op:
        batch_op.drop_index('unique_fecha_hora_bloqueo')

    # ### end Alembic commands ###
