"""empty message

Revision ID: 3932a6ac8181
Revises: 16f803863e06
Create Date: 2025-05-28 18:28:50.797275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3932a6ac8181'
down_revision = '16f803863e06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bloqueo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bloqueo', schema=None) as batch_op:
        batch_op.drop_column('motivo')

    # ### end Alembic commands ###
