"""empty message

Revision ID: 5bc074892c2b
Revises: 
Create Date: 2025-05-23 20:58:34.757581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bc074892c2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('servicio', sa.String(length=100), nullable=True),
    sa.Column('token', sa.String(length=50), nullable=False),
    sa.Column('cancelada', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.create_index('unique_fecha_hora_active_reservas', ['fecha', 'hora'], unique=True, postgresql_where=sa.text('cancelada = false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.drop_index('unique_fecha_hora_active_reservas', postgresql_where=sa.text('cancelada = false'))

    op.drop_table('reserva')
    # ### end Alembic commands ###
