"""empty message

Revision ID: ece67803a46e
Revises: 5163a2817770
Create Date: 2025-07-12 15:45:05.531415

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ece67803a46e'
down_revision = '5163a2817770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('variante_precio', sa.String(length=100), nullable=True))
        batch_op.alter_column('cancelada',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('creado_en',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('testimonio', schema=None) as batch_op:
        batch_op.alter_column('estrellas',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonio', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('estrellas',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('cancelada',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('variante_precio')
        batch_op.drop_column('direccion')

    # ### end Alembic commands ###
